enableScripts: false

packageExtensions:
  "@storybook/mdx1-csf@*":
    dependencies:
      "@babel/core": "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/docs-tools@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/instrumenter@*":
    dependencies:
      core-js: "*"
      react: "17.0.2"
      react-dom: "17.0.2"
  "stylelint-config-recommended-scss@*":
    dependencies:
      postcss: "*"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
